DROP DATABASE IF EXISTS hortitrol;

CREATE DATABASE hortitrol;
USE hortitrol;

/* variety schemas */

CREATE TABLE varieties (
	id INT AUTO_INCREMENT PRIMARY KEY,
	varietyName VARCHAR(155) NOT NULL UNIQUE,
	plantType VARCHAR(155) NOT NULL,
	dateCreated TIMESTAMP NOT NULL DEFAULT NOW(),
	slug VARCHAR(155) NOT NULL,
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE varietiesURLs (
	id INT AUTO_INCREMENT PRIMARY KEY,
	varietyID INT NOT NULL,
	varietyURL VARCHAR(155) NOT NULL,
	dateCreated TIMESTAMP NOT NULL DEFAULT NOW(),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY(varietyID) REFERENCES varieties(id)
);

CREATE TABLE varietiesPhotos (
	id INT AUTO_INCREMENT PRIMARY KEY,
	varietyID INT NOT NULL,
	imgURL VARCHAR(155) NOT NULL,
	dateCreated TIMESTAMP NOT NULL DEFAULT NOW(),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
	FOREIGN KEY(varietyID) REFERENCES varieties(id)
);



/* batch schemas */

CREATE TABLE trays (
	id INT AUTO_INCREMENT PRIMARY KEY,
	size INT NOT NULL DEFAULT 1,
	trayName VARCHAR(55) UNIQUE NOT NULL,
	hashID VARCHAR(45),
	createdDate DATETIME NOT NULL DEFAULT NOW(),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE batches (
	id INT AUTO_INCREMENT PRIMARY KEY,
	varietyID INT NOT NULL,
	trayID INT NOT NULL,
	activeStatus INT NOT NULL DEFAULT 1,
	qtyPlanted INT NOT NULL DEFAULT 1,
	qtyGerminated INT NOT NULL DEFAULT 0,
	sewnDate DATETIME NOT NULL DEFAULT NOW(),
	germinatedDate DATETIME,
	trayPositons VARCHAR(155),
	hashID VARCHAR(45),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
	FOREIGN KEY(varietyID) REFERENCES varieties(id),
	FOREIGN KEY(trayID) REFERENCES trays(id)
);

CREATE TABLE batchComments (
	id INT AUTO_INCREMENT PRIMARY KEY,
	batchID INT NOT NULL,
	batchComment VARCHAR(255) NOT NULL,
	createdDate DATETIME NOT NULL DEFAULT NOW(),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
	FOREIGN KEY(batchID) REFERENCES batches(id) 
);

CREATE TABLE batchMeasurements (
	id INT AUTO_INCREMENT PRIMARY KEY,
	batchID INT NOT NULL,
	measurement INT NOT NULL,
	createdDate DATETIME NOT NULL DEFAULT NOW(),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
	FOREIGN KEY(batchID) REFERENCES batches(id) 
);

CREATE TABLE batchPhotos (
	id INT AUTO_INCREMENT PRIMARY KEY,
	batchID INT NOT NULL,
	imgURL VARCHAR(155) NOT NULL,
	createdDate DATETIME NOT NULL DEFAULT NOW(),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
	FOREIGN KEY(batchID) REFERENCES batches(id) 
    
);

/* plant schemas */

CREATE TABLE pots (
	id INT AUTO_INCREMENT PRIMARY KEY,
	size VARCHAR(55) NOT NULL ,
	potName VARCHAR(55) UNIQUE NOT NULL,
	hashID VARCHAR(45) UNIQUE NOT NULL,
	activeStatus INT NOT NULL DEFAULT 1,
	createdDate DATETIME NOT NULL DEFAULT NOW(),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE plants (
	id INT AUTO_INCREMENT PRIMARY KEY,
	varietyID INT NOT NULL,
	potID INT NOT NULL,
	batchID INT DEFAULT 0,
	activeStatus INT NOT NULL DEFAULT 1,
	repottedDate1 DATETIME NOT NULL DEFAULT NOW(),
	repottedDate2 DATETIME,
	hashID VARCHAR(45),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
	FOREIGN KEY(varietyID) REFERENCES varieties(id),
	FOREIGN KEY(potID) REFERENCES pots(id),
	FOREIGN KEY(batchID) REFERENCES batches(id)
);

CREATE TABLE plantsComments (
	id INT AUTO_INCREMENT PRIMARY KEY,
	plantID INT NOT NULL,
	plantComment VARCHAR(255) NOT NULL,
	createdDate TIMESTAMP NOT NULL DEFAULT NOW(),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY(plantID) REFERENCES plants(id)
);

CREATE TABLE plantsMeasurements (
	id INT AUTO_INCREMENT PRIMARY KEY,
	plantID INT NOT NULL,
	measurement INT NOT NULL,
	createdDate TIMESTAMP NOT NULL DEFAULT NOW(),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY(plantID) REFERENCES plants(id)
);

CREATE TABLE plantsPhotos (
	id INT AUTO_INCREMENT PRIMARY KEY,
	plantID INT NOT NULL,
	imgURL VARCHAR(155) NOT NULL,
	createdDate TIMESTAMP NOT NULL DEFAULT NOW(),
	editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY(plantID) REFERENCES plants(id)    
);