CREATE TABLE varieties (
	id INT AUTO_INCREMENT PRIMARY KEY,
    varietyName VARCHAR(155) NOT NULL UNIQUE,
    plantType VARCHAR(155) NOT NULL,
    dateCreated TIMESTAMP NOT NULL DEFAULT NOW(),
    slug VARCHAR(155) NOT NULL,
    editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE varietiesURLs (
	id INT AUTO_INCREMENT PRIMARY KEY,
    varietyID INT NOT NULL,
    varietyURL VARCHAR(155) NOT NULL,
    dateCreated TIMESTAMP NOT NULL DEFAULT NOW(),
    editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY(varietyID) REFERENCES varieties(id)
);

CREATE TABLE varietiesPhotos (
	id INT AUTO_INCREMENT PRIMARY KEY,
    varietyID INT NOT NULL,
    imgURL VARCHAR(155) NOT NULL,
    dateCreated TIMESTAMP NOT NULL DEFAULT NOW(),
    editDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY(varietyID) REFERENCES varieties(id)
);

-- DROP TABLE varietiesPhotos, varietiesURLs ;